### PR TITLE
Open file2

### PR DESCRIPTION
**Pull request by rk917**
This branch includes opening files, opening files from the command line, creating files that don't exist, saving files, and save as functionality.

### CODE REVIEW

**Review by Xynda — APPROVED** [review]
Looks good Robert, just want to note that technically in a Windows environment if the user puts in the file path plus name of the file with your save as implementation, they can technically set where they want to save their file as well. 

Example: C:\Users\username\Documents\justext\new\test2.txt placed in File Name, will save a file named test2.txt in that folder structure.

**Review by alexei-clay — APPROVED** [review]

**Review by julianfortune — CHANGES_REQUESTED** [review]
I merged master into this branch, and the cursor doesn't seem to work when a user opens a file (from menu or command line) 🤔

**Comment by rk917** [comment]
> I merged master into this branch, and the cursor doesn't seem to work when a user opens a file (from menu or command line) 🤔

This issue appears to be driven by the if statement in the addcursor function:

if cursor == len(buffer) {...}

If this is commented out, the cursor is appended to the end of the file as normal.  I'm not sure if this is the behavior we want (seems like the cursor usually starts at the beginning of the file?)  I could also set the cursor == to the length of the buffer, but I'm not sure what the thought process is with the if statement.  Let's discuss during the meeting today.

**Review by julianfortune — APPROVED** [review]
Great!

**Pull request merged**
